// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyMoiTruong.Data.EF;

#nullable disable

namespace QuanLyMoiTruong.Data.Migrations
{
    [DbContext(typeof(QuanLyMoiTruongDbContext))]
    [Migration("20231116080715_Initial4")]
    partial class Initial4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("AppUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserTokens", (string)null);
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.AppConfig", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("AppConfig", (string)null);
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppRole", (string)null);
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Piority")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUser", (string)null);
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.BaoCaoBaoVeMoiTruong", b =>
                {
                    b.Property<int>("IdBaoCaoBaoVeMoiTruong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBaoCaoBaoVeMoiTruong"));

                    b.Property<int?>("IdDuAn")
                        .HasColumnType("int");

                    b.Property<int?>("IdKhuCongNghiep")
                        .HasColumnType("int");

                    b.Property<string>("IdNguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("KhuKinhTe")
                        .HasColumnType("bit");

                    b.Property<int>("Lan")
                        .HasColumnType("int");

                    b.Property<string>("LoaiBaoCao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayBaoCao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenBaoCao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBaoCaoBaoVeMoiTruong");

                    b.HasIndex("IdDuAn");

                    b.HasIndex("IdKhuCongNghiep");

                    b.ToTable("BaoCaoBaoVeMoiTruong", (string)null);
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.BaoCaoQuanTracMoiTruong", b =>
                {
                    b.Property<int>("IdBaoCaoQuanTracMoiTruong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBaoCaoQuanTracMoiTruong"));

                    b.Property<int?>("DuAnIdDuAn")
                        .HasColumnType("int");

                    b.Property<int?>("IdDuAn")
                        .HasColumnType("int");

                    b.Property<int?>("IdKhuCongNghiep")
                        .HasColumnType("int");

                    b.Property<string>("IdNguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Lan")
                        .HasColumnType("int");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayBaoCao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenBaoCao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBaoCaoQuanTracMoiTruong");

                    b.HasIndex("DuAnIdDuAn");

                    b.HasIndex("IdKhuCongNghiep");

                    b.ToTable("BaoCaoQuanTracMoiTruong", (string)null);
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.BaoCaoThongKeNguonThai", b =>
                {
                    b.Property<int>("IdBaoCaoThongKeNguonThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBaoCaoThongKeNguonThai"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdDuAn")
                        .HasColumnType("int");

                    b.Property<int?>("IdKhuCongNghiep")
                        .HasColumnType("int");

                    b.Property<string>("IdNguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("KhuKinhTe")
                        .HasColumnType("bit");

                    b.Property<int>("Lan")
                        .HasColumnType("int");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayBaoCao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenBaoCao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBaoCaoThongKeNguonThai");

                    b.HasIndex("IdDuAn");

                    b.HasIndex("IdKhuCongNghiep");

                    b.ToTable("BaoCaoThongKeNguonThai", (string)null);
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.DiemQuanTrac", b =>
                {
                    b.Property<int>("IdDiemQuanTrac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDiemQuanTrac"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KinhDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Loai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDiemQuanTrac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViDo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDiemQuanTrac");

                    b.ToTable("DiemQuanTrac", (string)null);
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.DuAn", b =>
                {
                    b.Property<int>("IdDuAn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDuAn"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiayPhepDKKD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdKhuCongNghiep")
                        .HasColumnType("int");

                    b.Property<string>("IdNguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiHinhSanXuat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuyMo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDoanhNghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDuAn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiPhuTrachTNMT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ThuocKhuKinhTe")
                        .HasColumnType("bit");

                    b.HasKey("IdDuAn");

                    b.HasIndex("IdKhuCongNghiep");

                    b.ToTable("DuAn", (string)null);
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.FileTaiLieu", b =>
                {
                    b.Property<int>("IdFileTaiLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFileTaiLieu"));

                    b.Property<int>("IdFile")
                        .HasColumnType("int");

                    b.Property<string>("IdNguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdTaiLieu")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiFileTaiLieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhomTaiLieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdFileTaiLieu");

                    b.HasIndex("IdFile")
                        .IsUnique();

                    b.ToTable("FileTaiLieu", (string)null);
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.Files", b =>
                {
                    b.Property<int>("IdFile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFile"));

                    b.Property<string>("IdNguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LinkFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenFile")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFile");

                    b.ToTable("Files", (string)null);
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.GiayPhepMoiTruong", b =>
                {
                    b.Property<int>("IdGiayPhepMoiTruong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGiayPhepMoiTruong"));

                    b.Property<string>("CoQuanCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdDuAn")
                        .HasColumnType("int");

                    b.Property<int?>("IdKhuCongNghiep")
                        .HasColumnType("int");

                    b.Property<string>("IdNguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgayCap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoGiayPhep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenGiayPhep")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdGiayPhepMoiTruong");

                    b.HasIndex("IdDuAn");

                    b.HasIndex("IdKhuCongNghiep");

                    b.ToTable("GiayPhepMoiTruong", (string)null);
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.HoSoKiemTraXuPhat", b =>
                {
                    b.Property<int>("IdHoSoKiemTraXuPhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHoSoKiemTraXuPhat"));

                    b.Property<int?>("IdDuAn")
                        .HasColumnType("int");

                    b.Property<int?>("IdKhuCongNghiep")
                        .HasColumnType("int");

                    b.Property<string>("IdNguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Lan")
                        .HasColumnType("int");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenHoSo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHoSoKiemTraXuPhat");

                    b.HasIndex("IdDuAn");

                    b.HasIndex("IdKhuCongNghiep");

                    b.ToTable("HoSoKiemTraXuPhat", (string)null);
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.KetQuaBaoVeMoiTruongDoanhNghiep", b =>
                {
                    b.Property<int>("IdKetQuaBaoVeMoiTruongDoanhNghiep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKetQuaBaoVeMoiTruongDoanhNghiep"));

                    b.Property<string>("ChatThaiRanCongNghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChatThaiRanNguyHai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChatThaiRanSinhHoat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DauNoiVaoHTXLNT")
                        .HasColumnType("bit");

                    b.Property<int>("IdBaoCaoBaoVeMoiTruong")
                        .HasColumnType("int");

                    b.Property<int>("IdDoanhNghiep")
                        .HasColumnType("int");

                    b.Property<int>("IdKhuCongNghiep")
                        .HasColumnType("int");

                    b.Property<string>("IdNguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiHinhSanXuat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LuongKhiThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("QuanTracKhiThai")
                        .HasColumnType("bit");

                    b.Property<string>("SoGiayTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TachDauNoi")
                        .HasColumnType("bit");

                    b.Property<string>("TenDoanhNghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhuCongNghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TongLuongNuocThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TyLeCayXanh")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKetQuaBaoVeMoiTruongDoanhNghiep");

                    b.HasIndex("IdBaoCaoBaoVeMoiTruong");

                    b.ToTable("KetQuaBaoVeMoiTruongDoanhNghiep", (string)null);
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.KetQuaBaoVeMoiTruongKCN", b =>
                {
                    b.Property<int>("IdKetQuaBaoVeMoiTruongKCN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKetQuaBaoVeMoiTruongKCN"));

                    b.Property<string>("ChatThaiRanCongNghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChatThaiRanNguyHai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChatThaiRanSinhHoat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CongSuatThietKeHTXLNT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CongTrinhPhongNgua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienTich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeThongQuanTracNuocThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HeThongThuGomNuocMua")
                        .HasColumnType("bit");

                    b.Property<int>("IdBaoCaoBaoVeMoiTruong")
                        .HasColumnType("int");

                    b.Property<int>("IdKhuCongNghiep")
                        .HasColumnType("int");

                    b.Property<string>("IdNguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuongCoSo")
                        .HasColumnType("int");

                    b.Property<string>("TenChuDautu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhuCongNghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TongLuongNuocThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TyLeCayXanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TyLeLapDay")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKetQuaBaoVeMoiTruongKCN");

                    b.HasIndex("IdBaoCaoBaoVeMoiTruong");

                    b.ToTable("KetQuaBaoVeMoiTruongKCN", (string)null);
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.KetQuaQuanTrac", b =>
                {
                    b.Property<int>("IdKetQuaQuanTrac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKetQuaQuanTrac"));

                    b.Property<string>("ChiTieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DonViTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiaTri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDiemQuanTrac")
                        .HasColumnType("int");

                    b.Property<string>("IdNguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdThanhPhanMoiTruong")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Lan")
                        .HasColumnType("int");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguongToiDa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguongToiThieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuChuan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKetQuaQuanTrac");

                    b.HasIndex("IdDiemQuanTrac");

                    b.HasIndex("IdThanhPhanMoiTruong");

                    b.ToTable("KetQuaQuanTrac", (string)null);
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.KetQuaThongKeNguonThai", b =>
                {
                    b.Property<int>("IdKetQuaThongKeNguonThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKetQuaThongKeNguonThai"));

                    b.Property<string>("ChatThaiNguyHai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChatThaiRanSanXuat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChatThaiRanSinhHoat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChatThaiRanTaiSuDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdBaoCaoThongKeNguonThai")
                        .HasColumnType("int");

                    b.Property<int>("IdKhuCongNghiep")
                        .HasColumnType("int");

                    b.Property<string>("IdNguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KhiThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LuuLuongDauNoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NuocThaiSanXuat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NuocThaiSinhHoat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NuocThaiTaiSuDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhuCongNghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TongChatThaiRan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKetQuaThongKeNguonThai");

                    b.HasIndex("IdBaoCaoThongKeNguonThai");

                    b.ToTable("KetQuaThongKeNguonThai", (string)null);
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.KhuCongNghiep", b =>
                {
                    b.Property<int>("IdKhuCongNghiep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKhuCongNghiep"));

                    b.Property<string>("DiaDiem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChuDauTu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhuCongNghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ThuocKhuKinhTe")
                        .HasColumnType("bit");

                    b.HasKey("IdKhuCongNghiep");

                    b.ToTable("KhuCongNghiep", (string)null);
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.PhuongXa", b =>
                {
                    b.Property<int>("IdPhuongXa")
                        .HasColumnType("int");

                    b.Property<string>("Cap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdQuanHuyen")
                        .HasColumnType("int");

                    b.Property<int>("IdTinhThanh")
                        .HasColumnType("int");

                    b.Property<string>("TenPhuongXa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenQuanHuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTinhThanh")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPhuongXa");

                    b.HasIndex("IdQuanHuyen");

                    b.ToTable("PhuongXa", (string)null);
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.QuanHuyen", b =>
                {
                    b.Property<int>("IdQuanHuyen")
                        .HasColumnType("int");

                    b.Property<string>("Cap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdTinhThanh")
                        .HasColumnType("int");

                    b.Property<string>("TenQuanHuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTinhThanh")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdQuanHuyen");

                    b.HasIndex("IdTinhThanh");

                    b.ToTable("QuanHuyen", (string)null);
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.ThanhPhanMoiTruong", b =>
                {
                    b.Property<int>("IdThanhPhanMoiTruong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdThanhPhanMoiTruong"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Lan")
                        .HasColumnType("int");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThanhPhanMoiTruong")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdThanhPhanMoiTruong");

                    b.ToTable("ThanhPhanMoiTruong", (string)null);
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.TinhThanh", b =>
                {
                    b.Property<int>("IdTinhThanh")
                        .HasColumnType("int");

                    b.Property<string>("Cap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTinhThanh")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTinhThanh");

                    b.ToTable("TinhThanh", (string)null);
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.VanBanQuyPham", b =>
                {
                    b.Property<int>("IdVanBanQuyPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVanBanQuyPham"));

                    b.Property<string>("CoQuanBanHanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayBanHanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoKyHieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrichYeu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdVanBanQuyPham");

                    b.ToTable("VanBanQuyPham", (string)null);
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.ViecLam", b =>
                {
                    b.Property<int>("IdViecLam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdViecLam"));

                    b.Property<string>("DSIdDiaPhuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DSIdNganhNghe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DSIdPhucLoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaDiem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DonViThoiGian")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DonViTienTe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MucLuongToiDa")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MucLuongToiThieu")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MucUuTien")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayPheDuyet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuyenLoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThongTinKhac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThongTinNhaTuyenDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TuyenDungDenNgay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TuyenDungTuNgay")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPheDuyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("XepHang")
                        .HasColumnType("int");

                    b.Property<string>("YeuCau")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdViecLam");

                    b.ToTable("ViecLam", (string)null);
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.BaoCaoBaoVeMoiTruong", b =>
                {
                    b.HasOne("QuanLyMoiTruong.Data.Entities.DuAn", "DuAn")
                        .WithMany("DsBaoCaoBaoVeMoiTruong")
                        .HasForeignKey("IdDuAn");

                    b.HasOne("QuanLyMoiTruong.Data.Entities.KhuCongNghiep", "KhuCongNghiep")
                        .WithMany("DsBaoCaoBaoVeMoiTruong")
                        .HasForeignKey("IdKhuCongNghiep");

                    b.Navigation("DuAn");

                    b.Navigation("KhuCongNghiep");
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.BaoCaoQuanTracMoiTruong", b =>
                {
                    b.HasOne("QuanLyMoiTruong.Data.Entities.DuAn", "DuAn")
                        .WithMany()
                        .HasForeignKey("DuAnIdDuAn");

                    b.HasOne("QuanLyMoiTruong.Data.Entities.KhuCongNghiep", "KhuCongNghiep")
                        .WithMany("DsBaoCaoQuanTracMoiTruong")
                        .HasForeignKey("IdKhuCongNghiep");

                    b.Navigation("DuAn");

                    b.Navigation("KhuCongNghiep");
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.BaoCaoThongKeNguonThai", b =>
                {
                    b.HasOne("QuanLyMoiTruong.Data.Entities.DuAn", "DuAn")
                        .WithMany("DsBaoCaoThongKeNguonThai")
                        .HasForeignKey("IdDuAn");

                    b.HasOne("QuanLyMoiTruong.Data.Entities.KhuCongNghiep", "KhuCongNghiep")
                        .WithMany("DsBaoCaoThongKeNguonThai")
                        .HasForeignKey("IdKhuCongNghiep");

                    b.Navigation("DuAn");

                    b.Navigation("KhuCongNghiep");
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.DuAn", b =>
                {
                    b.HasOne("QuanLyMoiTruong.Data.Entities.KhuCongNghiep", "KhuCongNghiep")
                        .WithMany("DsDuAn")
                        .HasForeignKey("IdKhuCongNghiep");

                    b.Navigation("KhuCongNghiep");
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.FileTaiLieu", b =>
                {
                    b.HasOne("QuanLyMoiTruong.Data.Entities.Files", "File")
                        .WithOne("FileTaiLieu")
                        .HasForeignKey("QuanLyMoiTruong.Data.Entities.FileTaiLieu", "IdFile")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.GiayPhepMoiTruong", b =>
                {
                    b.HasOne("QuanLyMoiTruong.Data.Entities.DuAn", "DuAn")
                        .WithMany("DsGiayPhepMoiTruong")
                        .HasForeignKey("IdDuAn");

                    b.HasOne("QuanLyMoiTruong.Data.Entities.KhuCongNghiep", "KhuCongNghiep")
                        .WithMany("DsGiayPhepMoiTruong")
                        .HasForeignKey("IdKhuCongNghiep");

                    b.Navigation("DuAn");

                    b.Navigation("KhuCongNghiep");
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.HoSoKiemTraXuPhat", b =>
                {
                    b.HasOne("QuanLyMoiTruong.Data.Entities.DuAn", "DuAn")
                        .WithMany("DsHoSoKiemTraXuPhat")
                        .HasForeignKey("IdDuAn");

                    b.HasOne("QuanLyMoiTruong.Data.Entities.KhuCongNghiep", "KhuCongNghiep")
                        .WithMany("DsHoSoKiemTraXuPhat")
                        .HasForeignKey("IdKhuCongNghiep");

                    b.Navigation("DuAn");

                    b.Navigation("KhuCongNghiep");
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.KetQuaBaoVeMoiTruongDoanhNghiep", b =>
                {
                    b.HasOne("QuanLyMoiTruong.Data.Entities.BaoCaoBaoVeMoiTruong", "BaoCaoBaoVeMoiTruong")
                        .WithMany("DsKetQuaBaoVeMoiTruongDoanhNghiep")
                        .HasForeignKey("IdBaoCaoBaoVeMoiTruong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaoCaoBaoVeMoiTruong");
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.KetQuaBaoVeMoiTruongKCN", b =>
                {
                    b.HasOne("QuanLyMoiTruong.Data.Entities.BaoCaoBaoVeMoiTruong", "BaoCaoBaoVeMoiTruong")
                        .WithMany("DsKetQuaBaoVeMoiTruongKCN")
                        .HasForeignKey("IdBaoCaoBaoVeMoiTruong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaoCaoBaoVeMoiTruong");
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.KetQuaQuanTrac", b =>
                {
                    b.HasOne("QuanLyMoiTruong.Data.Entities.DiemQuanTrac", "DiemQuanTrac")
                        .WithMany("DsKetQuaQuanTrac")
                        .HasForeignKey("IdDiemQuanTrac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyMoiTruong.Data.Entities.ThanhPhanMoiTruong", "ThanhPhanMoiTruong")
                        .WithMany("DsKetQuaQuanTrac")
                        .HasForeignKey("IdThanhPhanMoiTruong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiemQuanTrac");

                    b.Navigation("ThanhPhanMoiTruong");
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.KetQuaThongKeNguonThai", b =>
                {
                    b.HasOne("QuanLyMoiTruong.Data.Entities.BaoCaoThongKeNguonThai", "BaoCaoThongKeNguonThai")
                        .WithMany("DsKetQuaThongKeNguonThai")
                        .HasForeignKey("IdBaoCaoThongKeNguonThai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaoCaoThongKeNguonThai");
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.PhuongXa", b =>
                {
                    b.HasOne("QuanLyMoiTruong.Data.Entities.QuanHuyen", "QuanHuyen")
                        .WithMany("DSPhuongXa")
                        .HasForeignKey("IdQuanHuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuanHuyen");
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.QuanHuyen", b =>
                {
                    b.HasOne("QuanLyMoiTruong.Data.Entities.TinhThanh", "TinhThanh")
                        .WithMany("DSQuanHuyen")
                        .HasForeignKey("IdTinhThanh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TinhThanh");
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.BaoCaoBaoVeMoiTruong", b =>
                {
                    b.Navigation("DsKetQuaBaoVeMoiTruongDoanhNghiep");

                    b.Navigation("DsKetQuaBaoVeMoiTruongKCN");
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.BaoCaoThongKeNguonThai", b =>
                {
                    b.Navigation("DsKetQuaThongKeNguonThai");
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.DiemQuanTrac", b =>
                {
                    b.Navigation("DsKetQuaQuanTrac");
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.DuAn", b =>
                {
                    b.Navigation("DsBaoCaoBaoVeMoiTruong");

                    b.Navigation("DsBaoCaoThongKeNguonThai");

                    b.Navigation("DsGiayPhepMoiTruong");

                    b.Navigation("DsHoSoKiemTraXuPhat");
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.Files", b =>
                {
                    b.Navigation("FileTaiLieu");
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.KhuCongNghiep", b =>
                {
                    b.Navigation("DsBaoCaoBaoVeMoiTruong");

                    b.Navigation("DsBaoCaoQuanTracMoiTruong");

                    b.Navigation("DsBaoCaoThongKeNguonThai");

                    b.Navigation("DsDuAn");

                    b.Navigation("DsGiayPhepMoiTruong");

                    b.Navigation("DsHoSoKiemTraXuPhat");
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.QuanHuyen", b =>
                {
                    b.Navigation("DSPhuongXa");
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.ThanhPhanMoiTruong", b =>
                {
                    b.Navigation("DsKetQuaQuanTrac");
                });

            modelBuilder.Entity("QuanLyMoiTruong.Data.Entities.TinhThanh", b =>
                {
                    b.Navigation("DSQuanHuyen");
                });
#pragma warning restore 612, 618
        }
    }
}
